flowchart TD
    subgraph Initialization
        D1["Setup Player Manager"]
        D2["Setup Discord RPC"]
        D3["Initialize Template Engine"]
        D4["Initialize Cache Manager"]
    end

    subgraph PlayerModule
        P1["Poll Players"]
        P2["Get Player Metadata"]
        P3["Compare with Old State"]
        I1{"Player State Changes?"}
    end

    subgraph CoverArtModule
        CA1{"Check Cache"}
        CA2["Process Cover Art"]
        CA3["Return Cached/Default URL"]
        CA4["Update Cache"]
    end

    subgraph TemplateModule
        T1["Process Templates"]
    end

    subgraph DiscordModule
        D5["Update Discord Rich Presence"]
    end

    Initialization --> MainLoop

    MainLoop["Main Loop"] --> P1
    P1 --> P2 --> P3 --> I1

    I1 --Yes--> parallel{{"Parallel Processing"}}
    I1 --No--> MainLoop
    parallel --> CA1
    parallel --> T1

    CA1 --Hit--> CA3
    CA1 --Miss--> CA2
    CA2 --> CA4
    CA4 --> CA3


    CA3 & T1 --> D5
    D5 --> MainLoop
