# ------------------
# Basic Settings
# ------------------
# Whether to clear Discord activity when media is paused
clear_on_pause = true

# How often to update Discord presence (in milliseconds)
interval = 2000

# ------------------
# Display Template
# ------------------
[template]
# Available template variables:
#
# Track Info (Available through MPRIS):
#   {{{title}}}           - Track title
#   {{{artists}}}         - Track artists
#   {{{album_name}}}      - Album name
#   {{{album_artists}}}   - Album artists
#   {{{track_number}}}    - Track position in album
#   {{{disc_number}}}     - Disc number
#   {{{genre}}}           - Track genre (if provided by player)
#   {{{composer}}}        - Track composer (if provided by player)
#
# Player Status (Available):
#   {{{player}}}          - Media player name
#   {{{status}}}          - Player status (Playing/Paused/Stopped)
#   {{{position}}}        - Current position (MM:SS)
#   {{{length}}}          - Track length (MM:SS)
#
# Available Handlebars Helpers:
# For more details, see:
# - Handlebars Documentation: https://docs.rs/handlebars/latest/handlebars/
# - Built-in Helpers Source: https://docs.rs/handlebars/latest/src/handlebars/helpers/helper_boolean.rs.html
#
# Built-in Helpers:
#   {{#if value}}...{{else}}...{{/if}}     - Conditional block
#   {{#unless value}}...{{/unless}}         - Negative conditional block
#   {{#each array}}...{{/each}}            - Iterate over array/list
#   {{#with obj}}...{{/with}}              - Change context
#   {{lookup obj "key"}}                    - Access object property
#   {{len value}}                          - Get length of array/string/object
#   {{eq value1 value2}}                    - Compare values for equality
#   {{gt value1 value2}}                    - Greater than comparison
#   {{gte value1 value2}}                   - Greater than or equal comparison
#   {{lt value1 value2}}                    - Less than comparison
#   {{lte value1 value2}}                   - Less than or equal comparison
#   {{and value1 value2}}                   - Logical AND
#   {{or value1 value2}}                    - Logical OR
#   {{not value}}                          - Logical NOT
#
# Helper Usage Examples:
#   {{#if title}}{{{title}}}{{else}}Unknown Title{{/if}}
#   {{#unless status}}No playback{{/unless}}
#   {{#if (eq status "Playing")}}Now Playing{{/if}}
#   {{#if (and title artists)}}{{title}} by {{artists}}{{/if}}
#   {{#if (gt track_number 0)}}Track {{track_number}}{{/if}}

# What appears on the first line of Discord presence
detail = "{{{title}}}"

# What appears on the second line of Discord presence
state = "{{{artists}}}"

# Text shown when hovering over the large image
large_text = "{{#if album_name includeZero=true}}{{{album_name}}}{{else}}{{{title}}}{{/if}}"

# Text shown when hovering over the small image
small_text = "Playing on {{{player}}}"

# Text shown when value is not found
unknown_text = ""

# ------------------
# Activity Types
# ------------------
# Available activity types: "listening", "watching", "playing", "competing"
[activity_type]
use_content_type = true
default = "listening"

# ------------------
# Time Settings
# ------------------
[time]
# Enable/disable time progress in Discord
show = true

# Time display mode:
# true = show elapsed time
# false = show remaining time
as_elapsed = false

# ------------------
# Cover Art Settings
# ------------------
[cover]
# Local cover art files to look for (if cover art is not found in the tag)
file_names = ["cover", "folder", "front", "album", "art"]

[cover.provider]
# Cover art providers (in order of preference)
provider = ["musicbrainz", "imgbb"]

[cover.provider.imgbb]
# Your ImgBB API key for cover art hosting
# api_key = "YOUR_IMGBB_API_KEY"

# ------------------
# Player Settings
# ------------------
# Default settings for all players
[player.default]

# Whether to ignore the player
ignore = false

# Discord application ID https://support-dev.discord.com/hc/en-us/articles/360028717192-Where-can-I-find-my-Application-Team-Server-ID
app_id = "1121632048155742288"

# Player icon URL
icon = "https://raw.githubusercontent.com/lazykern/mprisence/main/assets/icon.png"

# Show player icon in Discord (as small image)
show_icon = false

# Show discord rich presence for http/https streaming media
allow_streaming = false

# Override media type based activity types
# override_activity_type = "listening"

# ------------------
# Example Player-Specific Settings
# ------------------
# VLC Example
# [player.vlc_media_player]
# app_id = "1124968989538402334"
# icon = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/VLC_Icon.svg/1200px-VLC_Icon.svg.png"
# show_icon = false
# allow_streaming = true
# override_activity_type = "watching"

# CMUS Example
# [player.cmus]
# icon = "https://i.ibb.co/3zDHM1z/cmus.png"
# show_icon = true

# ------------------
# Browser Settings
# ------------------
# Commonly ignored browser media players
# [player.chrome]
# ignore = true

# [player."Mozilla Firefox"]
# ignore = true

# [player.mozilla_zen]
# ignore = true

# [player.brave]
# ignore = true
