name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps for dbus-python
        run: sudo apt install build-essential libdbus-glib-1-dev libgirepository1.0-dev
      - name: Install dbus-python
        run: pip install dbus-python
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
